# Generated by Django 5.1.3 on 2024-12-02 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='num_paginas',
            field=models.IntegerField(null=True, verbose_name='Numero de paginas'),
        ),
    ]
