# Generated by Django 5.1.3 on 2024-12-02 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_libro_num_paginas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True)),
                ('tema', models.CharField(max_length=50, unique=True)),
                ('frecuencia_publicacion', models.CharField(choices=[('Diaria', 'Diaria'), ('Semanal', 'Semanal'), ('Mensual', 'Mensual')], max_length=10, verbose_name='Frecuencia de publicación')),
                ('num_edicion', models.IntegerField(null=True, verbose_name='Numero edicion')),
            ],
        ),
    ]
